window.CARDS = Object.freeze([
  {id:"動物-01",category:"動物",answer:"小狗",emoji:"🐶",hint:"搖尾巴、汪汪叫",zhuyin:"ㄒㄧㄠˇ ㄍㄡˇ"},
  {id:"動物-02",category:"動物",answer:"小貓",emoji:"🐱",hint:"輕輕走、舔爪子",zhuyin:"ㄒㄧㄠˇ ㄇㄠ"},
  {id:"動物-03",category:"動物",answer:"兔子",emoji:"🐰",hint:"長耳朵、跳一跳",zhuyin:"ㄊㄨˋ ㄗ˙"},
  {id:"動物-04",category:"動物",answer:"大象",emoji:"🐘",hint:"用手當長鼻子",zhuyin:"ㄉㄚˋ ㄒㄧㄤˋ"},
  {id:"動物-05",category:"動物",answer:"獅子",emoji:"🦁",hint:"甩鬃毛、大聲吼",zhuyin:"ㄕ ㄗ˙"},
  {id:"動物-06",category:"動物",answer:"猴子",emoji:"🐒",hint:"抓癢、爬樹",zhuyin:"ㄏㄡˊ ㄗ˙"},
  {id:"動物-07",category:"動物",answer:"企鵝",emoji:"🐧",hint:"搖搖擺擺走",zhuyin:"ㄑㄧˋ ㄜˊ"},
  {id:"動物-08",category:"動物",answer:"長頸鹿",emoji:"🦒",hint:"伸長脖子吃葉子",zhuyin:"ㄔㄤˊ ㄐㄧㄥˇ ㄌㄨˋ"},
  {id:"動物-09",category:"動物",answer:"熊貓",emoji:"🐼",hint:"抱著竹子吃",zhuyin:"ㄒㄩㄥˊ ㄇㄠ"},
  {id:"動物-10",category:"動物",answer:"青蛙",emoji:"🐸",hint:"蹲低再跳高",zhuyin:"ㄑㄧㄥ ㄨㄚ"},
  {id:"動物-11",category:"動物",answer:"蝴蝶",emoji:"🦋",hint:"揮動美麗翅膀",zhuyin:"ㄏㄨˊ ㄉㄧㄝˊ"},
  {id:"動物-12",category:"動物",answer:"烏龜",emoji:"🐢",hint:"慢慢走、縮進殼",zhuyin:"ㄨ ㄍㄨㄟ"},
  {id:"動物-13",category:"動物",answer:"螃蟹",emoji:"🦀",hint:"橫著走、夾一夾",zhuyin:"ㄆㄤˊ ㄒㄧㄝˋ"},
  {id:"動物-14",category:"動物",answer:"海豚",emoji:"🐬",hint:"躍出水面",zhuyin:"ㄏㄞˇ ㄊㄨㄣˊ"},
  {id:"動物-15",category:"動物",answer:"貓頭鷹",emoji:"🦉",hint:"睜大眼睛轉頭",zhuyin:"ㄇㄠ ㄊㄡˊ ㄧㄥ"},
  {id:"動物-16",category:"動物",answer:"馬",emoji:"🐴",hint:"跑步、甩尾巴",zhuyin:"ㄇㄚˇ"},
  {id:"食物-01",category:"食物",answer:"蘋果",emoji:"🍎",hint:"咬一口脆脆的",zhuyin:"ㄆㄧㄥˊ ㄍㄨㄛˇ"},
  {id:"食物-02",category:"食物",answer:"香蕉",emoji:"🍌",hint:"剝皮再吃",zhuyin:"ㄒㄧㄤ ㄐㄧㄠ"},
  {id:"食物-03",category:"食物",answer:"西瓜",emoji:"🍉",hint:"抱著大大一顆",zhuyin:"ㄒㄧ ㄍㄨㄚ"},
  {id:"食物-04",category:"食物",answer:"披薩",emoji:"🍕",hint:"拉出長長起司",zhuyin:"ㄆㄧ ㄙㄚˋ"},
  {id:"食物-05",category:"食物",answer:"麵條",emoji:"🍜",hint:"用筷子吸麵",zhuyin:"ㄇㄧㄢˋ ㄊㄧㄠˊ"},
  {id:"食物-06",category:"食物",answer:"白飯",emoji:"🍚",hint:"捧碗一口口吃",zhuyin:"ㄅㄞˊ ㄈㄢˋ"},
  {id:"食物-07",category:"食物",answer:"紅蘿蔔",emoji:"🥕",hint:"兔子最喜歡",zhuyin:"ㄏㄨㄥˊ ㄌㄨㄛˊ ㄅㄛˊ"},
  {id:"食物-08",category:"食物",answer:"玉米",emoji:"🌽",hint:"一排一排啃",zhuyin:"ㄩˋ ㄇㄧˇ"},
  {id:"食物-09",category:"食物",answer:"冰淇淋",emoji:"🍦",hint:"舔一舔怕融化",zhuyin:"ㄅㄧㄥ ㄑㄧˊ ㄌㄧㄣˊ"},
  {id:"食物-10",category:"食物",answer:"甜甜圈",emoji:"🍩",hint:"圓圓中間有洞",zhuyin:"ㄊㄧㄢˊ ㄊㄧㄢˊ ㄑㄩㄢ"},
  {id:"食物-11",category:"食物",answer:"餅乾",emoji:"🍪",hint:"喀滋喀滋吃",zhuyin:"ㄅㄧㄥˇ ㄍㄢ"},
  {id:"食物-12",category:"食物",answer:"三明治",emoji:"🥪",hint:"兩手拿著大口咬",zhuyin:"ㄙㄢ ㄇㄧㄥˊ ㄓˋ"},
  {id:"食物-13",category:"食物",answer:"雞蛋",emoji:"🥚",hint:"敲開蛋殼",zhuyin:"ㄐㄧ ㄉㄢˋ"},
  {id:"食物-14",category:"食物",answer:"草莓",emoji:"🍓",hint:"小小紅紅有種子",zhuyin:"ㄘㄠˇ ㄇㄟˊ"},
  {id:"食物-15",category:"食物",answer:"水餃",emoji:"🥟",hint:"夾起來沾醬",zhuyin:"ㄕㄨㄟˇ ㄐㄧㄠˇ"},
  {id:"食物-16",category:"食物",answer:"爆米花",emoji:"🍿",hint:"看電影一顆顆吃",zhuyin:"ㄅㄠˋ ㄇㄧˇ ㄏㄨㄚ"},
  {id:"交通-01",category:"交通",answer:"汽車",emoji:"🚗",hint:"握方向盤開車",zhuyin:"ㄑㄧˋ ㄔㄜ"},
  {id:"交通-02",category:"交通",answer:"公車",emoji:"🚌",hint:"到站讓乘客下車",zhuyin:"ㄍㄨㄥ ㄔㄜ"},
  {id:"交通-03",category:"交通",answer:"腳踏車",emoji:"🚲",hint:"踩踏板、按鈴鐺",zhuyin:"ㄐㄧㄠˇ ㄊㄚˋ ㄔㄜ"},
  {id:"交通-04",category:"交通",answer:"飛機",emoji:"✈️",hint:"張開雙臂飛",zhuyin:"ㄈㄟ ㄐㄧ"},
  {id:"交通-05",category:"交通",answer:"火車",emoji:"🚂",hint:"嗚嗚叫向前跑",zhuyin:"ㄏㄨㄛˇ ㄔㄜ"},
  {id:"交通-06",category:"交通",answer:"輪船",emoji:"🚢",hint:"在海浪上航行",zhuyin:"ㄌㄨㄣˊ ㄔㄨㄢˊ"},
  {id:"交通-07",category:"交通",answer:"直升機",emoji:"🚁",hint:"頭頂螺旋槳轉動",zhuyin:"ㄓˊ ㄕㄥ ㄐㄧ"},
  {id:"交通-08",category:"交通",answer:"機車",emoji:"🛵",hint:"戴安全帽再騎",zhuyin:"ㄐㄧ ㄔㄜ"},
  {id:"交通-09",category:"交通",answer:"計程車",emoji:"🚕",hint:"招手上車",zhuyin:"ㄐㄧˋ ㄔㄥˊ ㄔㄜ"},
  {id:"交通-10",category:"交通",answer:"捷運",emoji:"🚇",hint:"刷卡進站",zhuyin:"ㄐㄧㄝˊ ㄩㄣˋ"},
  {id:"交通-11",category:"交通",answer:"獨木舟",emoji:"🛶",hint:"左右划船槳",zhuyin:"ㄉㄨˊ ㄇㄨˋ ㄓㄡ"},
  {id:"交通-12",category:"交通",answer:"火箭",emoji:"🚀",hint:"倒數後飛上天空",zhuyin:"ㄏㄨㄛˇ ㄐㄧㄢˋ"},
  {id:"交通-13",category:"交通",answer:"拖拉機",emoji:"🚜",hint:"在田裡慢慢開",zhuyin:"ㄊㄨㄛ ㄌㄚ ㄐㄧ"},
  {id:"交通-14",category:"交通",answer:"救護車",emoji:"🚑",hint:"閃燈趕去幫忙",zhuyin:"ㄐㄧㄡˋ ㄏㄨˋ ㄔㄜ"},
  {id:"交通-15",category:"交通",answer:"消防車",emoji:"🚒",hint:"伸水管救火",zhuyin:"ㄒㄧㄠ ㄈㄤˊ ㄔㄜ"},
  {id:"交通-16",category:"交通",answer:"滑板車",emoji:"🛴",hint:"一腳踩、一腳推",zhuyin:"ㄏㄨㄚˊ ㄅㄢˇ ㄔㄜ"},
  {id:"運動-01",category:"運動",answer:"踢足球",emoji:"⚽",hint:"用腳把球踢進門",zhuyin:"ㄊㄧ ㄗㄨˊ ㄑㄧㄡˊ"},
  {id:"運動-02",category:"運動",answer:"打籃球",emoji:"🏀",hint:"運球再投籃",zhuyin:"ㄉㄚˇ ㄌㄢˊ ㄑㄧㄡˊ"},
  {id:"運動-03",category:"運動",answer:"打棒球",emoji:"⚾",hint:"揮棒把球打遠",zhuyin:"ㄉㄚˇ ㄅㄤˋ ㄑㄧㄡˊ"},
  {id:"運動-04",category:"運動",answer:"游泳",emoji:"🏊",hint:"雙手划水前進",zhuyin:"ㄧㄡˊ ㄩㄥˇ"},
  {id:"運動-05",category:"運動",answer:"打羽球",emoji:"🏸",hint:"拿球拍向上打",zhuyin:"ㄉㄚˇ ㄩˇ ㄑㄧㄡˊ"},
  {id:"運動-06",category:"運動",answer:"打桌球",emoji:"🏓",hint:"小球快速來回",zhuyin:"ㄉㄚˇ ㄓㄨㄛ ㄑㄧㄡˊ"},
  {id:"運動-07",category:"運動",answer:"打網球",emoji:"🎾",hint:"大力揮拍過網",zhuyin:"ㄉㄚˇ ㄨㄤˇ ㄑㄧㄡˊ"},
  {id:"運動-08",category:"運動",answer:"跳繩",emoji:"⛹️",hint:"甩繩子一直跳",zhuyin:"ㄊㄧㄠˋ ㄕㄥˊ"},
  {id:"運動-09",category:"運動",answer:"跑步",emoji:"🏃",hint:"手腳快速擺動",zhuyin:"ㄆㄠˇ ㄅㄨˋ"},
  {id:"運動-10",category:"運動",answer:"做瑜伽",emoji:"🧘",hint:"安靜伸展身體",zhuyin:"ㄗㄨㄛˋ ㄩˊ ㄐㄧㄚ"},
  {id:"運動-11",category:"運動",answer:"溜冰",emoji:"⛸️",hint:"在冰上滑行",zhuyin:"ㄌㄧㄡ ㄅㄧㄥ"},
  {id:"運動-12",category:"運動",answer:"跆拳道",emoji:"🥋",hint:"踢腿後敬禮",zhuyin:"ㄊㄞˊ ㄑㄩㄢˊ ㄉㄠˋ"},
  {id:"運動-13",category:"運動",answer:"打保齡球",emoji:"🎳",hint:"滾球擊倒瓶子",zhuyin:"ㄉㄚˇ ㄅㄠˇ ㄌㄧㄥˊ ㄑㄧㄡˊ"},
  {id:"運動-14",category:"運動",answer:"衝浪",emoji:"🏄",hint:"站在海浪上平衡",zhuyin:"ㄔㄨㄥ ㄌㄤˋ"},
  {id:"運動-15",category:"運動",answer:"丟飛盤",emoji:"🥏",hint:"把飛盤拋向朋友",zhuyin:"ㄉㄧㄡ ㄈㄟ ㄆㄢˊ"},
  {id:"運動-16",category:"運動",answer:"打排球",emoji:"🏐",hint:"雙手把球托高",zhuyin:"ㄉㄚˇ ㄆㄞˊ ㄑㄧㄡˊ"},
  {id:"職業-01",category:"職業",answer:"老師",emoji:"👩‍🏫",hint:"拿粉筆教大家",zhuyin:"ㄌㄠˇ ㄕ"},
  {id:"職業-02",category:"職業",answer:"醫生",emoji:"👨‍⚕️",hint:"用聽診器檢查",zhuyin:"ㄧ ㄕㄥ"},
  {id:"職業-03",category:"職業",answer:"消防員",emoji:"👩‍🚒",hint:"拿水管幫忙滅火",zhuyin:"ㄒㄧㄠ ㄈㄤˊ ㄩㄢˊ"},
  {id:"職業-04",category:"職業",answer:"警察",emoji:"👮",hint:"指揮交通保護大家",zhuyin:"ㄐㄧㄥˇ ㄔㄚˊ"},
  {id:"職業-05",category:"職業",answer:"廚師",emoji:"👨‍🍳",hint:"翻炒鍋裡的菜",zhuyin:"ㄔㄨˊ ㄕ"},
  {id:"職業-06",category:"職業",answer:"農夫",emoji:"👩‍🌾",hint:"播種再澆水",zhuyin:"ㄋㄨㄥˊ ㄈㄨ"},
  {id:"職業-07",category:"職業",answer:"太空人",emoji:"👨‍🚀",hint:"在無重力中漂浮",zhuyin:"ㄊㄞˋ ㄎㄨㄥ ㄖㄣˊ"},
  {id:"職業-08",category:"職業",answer:"畫家",emoji:"👩‍🎨",hint:"拿畫筆畫大圖",zhuyin:"ㄏㄨㄚˋ ㄐㄧㄚ"},
  {id:"職業-09",category:"職業",answer:"修理師",emoji:"👨‍🔧",hint:"拿工具轉螺絲",zhuyin:"ㄒㄧㄡ ㄌㄧˇ ㄕ"},
  {id:"職業-10",category:"職業",answer:"科學家",emoji:"👩‍🔬",hint:"觀察試管做實驗",zhuyin:"ㄎㄜ ㄒㄩㄝˊ ㄐㄧㄚ"},
  {id:"職業-11",category:"職業",answer:"飛行員",emoji:"👨‍✈️",hint:"操縱飛機起飛",zhuyin:"ㄈㄟ ㄒㄧㄥˊ ㄩㄢˊ"},
  {id:"職業-12",category:"職業",answer:"理髮師",emoji:"💇",hint:"幫客人修剪頭髮",zhuyin:"ㄌㄧˇ ㄈㄚˇ ㄕ"},
  {id:"職業-13",category:"職業",answer:"攝影師",emoji:"📷",hint:"舉相機按快門",zhuyin:"ㄕㄜˋ ㄧㄥˇ ㄕ"},
  {id:"職業-14",category:"職業",answer:"護理師",emoji:"🧑‍⚕️",hint:"溫柔照顧病人",zhuyin:"ㄏㄨˋ ㄌㄧˇ ㄕ"},
  {id:"職業-15",category:"職業",answer:"圖書館員",emoji:"📚",hint:"整理書本保持安靜",zhuyin:"ㄊㄨˊ ㄕㄨ ㄍㄨㄢˇ ㄩㄢˊ"},
  {id:"職業-16",category:"職業",answer:"郵差",emoji:"📮",hint:"背信件送到家",zhuyin:"ㄧㄡˊ ㄔㄞ"},
  {id:"日常動作-01",category:"日常動作",answer:"刷牙",emoji:"🪥",hint:"上下左右刷乾淨",zhuyin:"ㄕㄨㄚ ㄧㄚˊ"},
  {id:"日常動作-02",category:"日常動作",answer:"洗手",emoji:"🧼",hint:"搓泡泡沖乾淨",zhuyin:"ㄒㄧˇ ㄕㄡˇ"},
  {id:"日常動作-03",category:"日常動作",answer:"睡覺",emoji:"😴",hint:"閉眼打呼",zhuyin:"ㄕㄨㄟˋ ㄐㄩㄝˊ"},
  {id:"日常動作-04",category:"日常動作",answer:"打哈欠",emoji:"🥱",hint:"張大嘴巴伸懶腰",zhuyin:"ㄉㄚˇ ㄏㄚ ㄑㄧㄢˋ"},
  {id:"日常動作-05",category:"日常動作",answer:"拍手",emoji:"👏",hint:"兩手碰在一起",zhuyin:"ㄆㄞ ㄕㄡˇ"},
  {id:"日常動作-06",category:"日常動作",answer:"揮手",emoji:"👋",hint:"左右揮說再見",zhuyin:"ㄏㄨㄟ ㄕㄡˇ"},
  {id:"日常動作-07",category:"日常動作",answer:"打噴嚏",emoji:"🤧",hint:"用手肘遮住口鼻",zhuyin:"ㄉㄚˇ ㄆㄣ ㄊㄧˋ"},
  {id:"日常動作-08",category:"日常動作",answer:"看書",emoji:"📖",hint:"翻頁仔細閱讀",zhuyin:"ㄎㄢˋ ㄕㄨ"},
  {id:"日常動作-09",category:"日常動作",answer:"寫字",emoji:"✍️",hint:"握筆一筆一畫",zhuyin:"ㄒㄧㄝˇ ㄗˋ"},
  {id:"日常動作-10",category:"日常動作",answer:"掃地",emoji:"🧹",hint:"拿掃把掃乾淨",zhuyin:"ㄙㄠˇ ㄉㄧˋ"},
  {id:"日常動作-11",category:"日常動作",answer:"曬衣服",emoji:"🧺",hint:"把衣服夾上去",zhuyin:"ㄕㄞˋ ㄧ ㄈㄨˊ"},
  {id:"日常動作-12",category:"日常動作",answer:"打電話",emoji:"📞",hint:"手機放耳邊說話",zhuyin:"ㄉㄚˇ ㄉㄧㄢˋ ㄏㄨㄚˋ"},
  {id:"日常動作-13",category:"日常動作",answer:"拆禮物",emoji:"🎁",hint:"打開盒子好驚喜",zhuyin:"ㄔㄞ ㄌㄧˇ ㄨˋ"},
  {id:"日常動作-14",category:"日常動作",answer:"澆花",emoji:"🪴",hint:"拿水壺慢慢倒",zhuyin:"ㄐㄧㄠ ㄏㄨㄚ"},
  {id:"日常動作-15",category:"日常動作",answer:"穿鞋",emoji:"👟",hint:"套進腳再綁鞋帶",zhuyin:"ㄔㄨㄢ ㄒㄧㄝˊ"},
  {id:"日常動作-16",category:"日常動作",answer:"煎蛋",emoji:"🍳",hint:"打蛋下鍋翻一翻",zhuyin:"ㄐㄧㄢ ㄉㄢˋ"},
  {id:"生活物品-01",category:"生活物品",answer:"雨傘",emoji:"☂️",hint:"下雨撐開擋雨",zhuyin:"ㄩˇ ㄙㄢˇ"},
  {id:"生活物品-02",category:"生活物品",answer:"鬧鐘",emoji:"⏰",hint:"時間到鈴鈴響",zhuyin:"ㄋㄠˋ ㄓㄨㄥ"},
  {id:"生活物品-03",category:"生活物品",answer:"手電筒",emoji:"🔦",hint:"黑暗中照亮前方",zhuyin:"ㄕㄡˇ ㄉㄧㄢˋ ㄊㄨㄥˇ"},
  {id:"生活物品-04",category:"生活物品",answer:"椅子",emoji:"🪑",hint:"拉開再坐下",zhuyin:"ㄧˇ ㄗ˙"},
  {id:"生活物品-05",category:"生活物品",answer:"床",emoji:"🛏️",hint:"躺下蓋棉被",zhuyin:"ㄔㄨㄤˊ"},
  {id:"生活物品-06",category:"生活物品",answer:"玩具熊",emoji:"🧸",hint:"抱在懷裡軟綿綿",zhuyin:"ㄨㄢˊ ㄐㄩˋ ㄒㄩㄥˊ"},
  {id:"生活物品-07",category:"生活物品",answer:"書包",emoji:"🎒",hint:"背著去上學",zhuyin:"ㄕㄨ ㄅㄠ"},
  {id:"生活物品-08",category:"生活物品",answer:"鉛筆",emoji:"✏️",hint:"寫錯可以擦掉",zhuyin:"ㄑㄧㄢ ㄅㄧˇ"},
  {id:"生活物品-09",category:"生活物品",answer:"橡皮擦",emoji:"🧽",hint:"把鉛筆字擦掉",zhuyin:"ㄒㄧㄤˋ ㄆㄧˊ ㄘㄚ"},
  {id:"生活物品-10",category:"生活物品",answer:"水壺",emoji:"🧴",hint:"打開蓋子喝水",zhuyin:"ㄕㄨㄟˇ ㄏㄨˊ"},
  {id:"生活物品-11",category:"生活物品",answer:"鏡子",emoji:"🪞",hint:"照一照整理頭髮",zhuyin:"ㄐㄧㄥˋ ㄗ˙"},
  {id:"生活物品-12",category:"生活物品",answer:"衛生紙",emoji:"🧻",hint:"抽一張擦乾淨",zhuyin:"ㄨㄟˋ ㄕㄥ ㄓˇ"},
  {id:"生活物品-13",category:"生活物品",answer:"鑰匙",emoji:"🔑",hint:"插進鎖孔轉一轉",zhuyin:"ㄧㄠˋ ㄕ˙"},
  {id:"生活物品-14",category:"生活物品",answer:"襪子",emoji:"🧦",hint:"一隻腳穿一隻",zhuyin:"ㄨㄚˋ ㄗ˙"},
  {id:"生活物品-15",category:"生活物品",answer:"帽子",emoji:"🧢",hint:"戴在頭上遮太陽",zhuyin:"ㄇㄠˋ ㄗ˙"},
  {id:"生活物品-16",category:"生活物品",answer:"沙發",emoji:"🛋️",hint:"舒服坐下休息",zhuyin:"ㄕㄚ ㄈㄚ"},
  {id:"自然幻想-01",category:"自然幻想",answer:"太陽",emoji:"☀️",hint:"高高掛著發光發熱",zhuyin:"ㄊㄞˋ ㄧㄤˊ"},
  {id:"自然幻想-02",category:"自然幻想",answer:"下雨",emoji:"🌧️",hint:"手指變雨滴落下",zhuyin:"ㄒㄧㄚˋ ㄩˇ"},
  {id:"自然幻想-03",category:"自然幻想",answer:"彩虹",emoji:"🌈",hint:"彎彎有好多顏色",zhuyin:"ㄘㄞˇ ㄏㄨㄥˊ"},
  {id:"自然幻想-04",category:"自然幻想",answer:"龍捲風",emoji:"🌪️",hint:"身體旋轉捲起來",zhuyin:"ㄌㄨㄥˊ ㄐㄩㄢˇ ㄈㄥ"},
  {id:"自然幻想-05",category:"自然幻想",answer:"雪花",emoji:"❄️",hint:"輕飄飄落下融化",zhuyin:"ㄒㄩㄝˇ ㄏㄨㄚ"},
  {id:"自然幻想-06",category:"自然幻想",answer:"海浪",emoji:"🌊",hint:"雙手起伏拍岸",zhuyin:"ㄏㄞˇ ㄌㄤˋ"},
  {id:"自然幻想-07",category:"自然幻想",answer:"火山",emoji:"🌋",hint:"從山頂噴發",zhuyin:"ㄏㄨㄛˇ ㄕㄢ"},
  {id:"自然幻想-08",category:"自然幻想",answer:"大樹",emoji:"🌳",hint:"站直張開枝葉",zhuyin:"ㄉㄚˋ ㄕㄨˋ"},
  {id:"自然幻想-09",category:"自然幻想",answer:"向日葵",emoji:"🌻",hint:"跟著太陽轉頭",zhuyin:"ㄒㄧㄤˋ ㄖˋ ㄎㄨㄟˊ"},
  {id:"自然幻想-10",category:"自然幻想",answer:"月亮",emoji:"🌙",hint:"夜晚彎彎掛天空",zhuyin:"ㄩㄝˋ ㄌㄧㄤˋ"},
  {id:"自然幻想-11",category:"自然幻想",answer:"星星",emoji:"⭐",hint:"在天空閃呀閃",zhuyin:"ㄒㄧㄥ ㄒㄧㄥ"},
  {id:"自然幻想-12",category:"自然幻想",answer:"獨角獸",emoji:"🦄",hint:"頭上有角優雅奔跑",zhuyin:"ㄉㄨˊ ㄐㄧㄠˇ ㄕㄡˋ"},
  {id:"自然幻想-13",category:"自然幻想",answer:"小飛龍",emoji:"🐉",hint:"拍翅膀吐出彩煙",zhuyin:"ㄒㄧㄠˇ ㄈㄟ ㄌㄨㄥˊ"},
  {id:"自然幻想-14",category:"自然幻想",answer:"小仙子",emoji:"🧚",hint:"揮魔法棒飛舞",zhuyin:"ㄒㄧㄠˇ ㄒㄧㄢ ㄗˇ"},
  {id:"自然幻想-15",category:"自然幻想",answer:"人魚",emoji:"🧜",hint:"擺動尾巴游泳",zhuyin:"ㄖㄣˊ ㄩˊ"},
  {id:"自然幻想-16",category:"自然幻想",answer:"白雲",emoji:"☁️",hint:"軟綿綿飄過天空",zhuyin:"ㄅㄞˊ ㄩㄣˊ"},
  {id:"擴充-001",category:"綜合擴充題",answer:"松鼠",emoji:"🐿️",hint:"抱著果實快速啃",zhuyin:"ㄙㄨㄥ ㄕㄨˇ"},
  {id:"擴充-002",category:"綜合擴充題",answer:"無尾熊",emoji:"🐨",hint:"抱緊樹幹睡覺",zhuyin:"ㄨˊ ㄨㄟˇ ㄒㄩㄥˊ"},
  {id:"擴充-003",category:"綜合擴充題",answer:"老虎",emoji:"🐯",hint:"張開爪子大聲吼",zhuyin:"ㄌㄠˇ ㄏㄨˇ"},
  {id:"擴充-004",category:"綜合擴充題",answer:"斑馬",emoji:"🦓",hint:"展示身上的黑白條紋",zhuyin:"ㄅㄢ ㄇㄚˇ"},
  {id:"擴充-005",category:"綜合擴充題",answer:"河馬",emoji:"🦛",hint:"張開超大的嘴巴",zhuyin:"ㄏㄜˊ ㄇㄚˇ"},
  {id:"擴充-006",category:"綜合擴充題",answer:"犀牛",emoji:"🦏",hint:"手放鼻前當尖角",zhuyin:"ㄒㄧ ㄋㄧㄡˊ"},
  {id:"擴充-007",category:"綜合擴充題",answer:"袋鼠",emoji:"🦘",hint:"抱著肚前口袋跳",zhuyin:"ㄉㄞˋ ㄕㄨˇ"},
  {id:"擴充-008",category:"綜合擴充題",answer:"駱駝",emoji:"🐫",hint:"背著駝峰走沙漠",zhuyin:"ㄌㄨㄛˋ ㄊㄨㄛˊ"},
  {id:"擴充-009",category:"綜合擴充題",answer:"狐狸",emoji:"🦊",hint:"豎起耳朵悄悄走",zhuyin:"ㄏㄨˊ ㄌㄧˊ"},
  {id:"擴充-010",category:"綜合擴充題",answer:"狼",emoji:"🐺",hint:"抬頭對月亮嚎叫",zhuyin:"ㄌㄤˊ"},
  {id:"擴充-011",category:"綜合擴充題",answer:"刺蝟",emoji:"🦔",hint:"縮成一顆刺刺球",zhuyin:"ㄘˋ ㄨㄟˋ"},
  {id:"擴充-012",category:"綜合擴充題",answer:"水獺",emoji:"🦦",hint:"仰躺水面拍肚子",zhuyin:"ㄕㄨㄟˇ ㄊㄚˋ"},
  {id:"擴充-013",category:"綜合擴充題",answer:"海豹",emoji:"🦭",hint:"拍著前鰭滑行",zhuyin:"ㄏㄞˇ ㄅㄠˋ"},
  {id:"擴充-014",category:"綜合擴充題",answer:"鯨魚",emoji:"🐋",hint:"噴出高高的水柱",zhuyin:"ㄐㄧㄥ ㄩˊ"},
  {id:"擴充-015",category:"綜合擴充題",answer:"鯊魚",emoji:"🦈",hint:"露出背鰭游一圈",zhuyin:"ㄕㄚ ㄩˊ"},
  {id:"擴充-016",category:"綜合擴充題",answer:"章魚",emoji:"🐙",hint:"八隻手到處揮動",zhuyin:"ㄓㄤ ㄩˊ"},
  {id:"擴充-017",category:"綜合擴充題",answer:"水母",emoji:"🪼",hint:"身體軟軟漂浮",zhuyin:"ㄕㄨㄟˇ ㄇㄨˇ"},
  {id:"擴充-018",category:"綜合擴充題",answer:"熱帶魚",emoji:"🐠",hint:"擺動尾巴游來游去",zhuyin:"ㄖㄜˋ ㄉㄞˋ ㄩˊ"},
  {id:"擴充-019",category:"綜合擴充題",answer:"河豚",emoji:"🐡",hint:"吸氣鼓成大圓球",zhuyin:"ㄏㄜˊ ㄊㄨㄣˊ"},
  {id:"擴充-020",category:"綜合擴充題",answer:"鱷魚",emoji:"🐊",hint:"張開長嘴慢慢爬",zhuyin:"ㄜˋ ㄩˊ"},
  {id:"擴充-021",category:"綜合擴充題",answer:"蛇",emoji:"🐍",hint:"身體彎曲向前滑",zhuyin:"ㄕㄜˊ"},
  {id:"擴充-022",category:"綜合擴充題",answer:"蝸牛",emoji:"🐌",hint:"背著殼慢慢移動",zhuyin:"ㄍㄨㄚ ㄋㄧㄡˊ"},
  {id:"擴充-023",category:"綜合擴充題",answer:"蜜蜂",emoji:"🐝",hint:"拍翅膀採花蜜",zhuyin:"ㄇㄧˋ ㄈㄥ"},
  {id:"擴充-024",category:"綜合擴充題",answer:"螞蟻",emoji:"🐜",hint:"搬著食物排隊走",zhuyin:"ㄇㄚˇ ㄧˇ"},
  {id:"擴充-025",category:"綜合擴充題",answer:"鸚鵡",emoji:"🦜",hint:"站在肩上學說話",zhuyin:"ㄧㄥ ㄨˇ"},
  {id:"擴充-026",category:"綜合擴充題",answer:"橘子",emoji:"🍊",hint:"剝開果皮一瓣瓣吃",zhuyin:"ㄐㄩˊ ㄗ˙"},
  {id:"擴充-027",category:"綜合擴充題",answer:"葡萄",emoji:"🍇",hint:"摘下一顆放嘴裡",zhuyin:"ㄆㄨˊ ㄊㄠˊ"},
  {id:"擴充-028",category:"綜合擴充題",answer:"桃子",emoji:"🍑",hint:"捧著圓果實咬一口",zhuyin:"ㄊㄠˊ ㄗ˙"},
  {id:"擴充-029",category:"綜合擴充題",answer:"梨子",emoji:"🍐",hint:"拿著上小下大的水果",zhuyin:"ㄌㄧˊ ㄗ˙"},
  {id:"擴充-030",category:"綜合擴充題",answer:"櫻桃",emoji:"🍒",hint:"兩顆小果實連一起",zhuyin:"ㄧㄥ ㄊㄠˊ"},
  {id:"擴充-031",category:"綜合擴充題",answer:"藍莓",emoji:"🫐",hint:"抓起小果實一顆顆吃",zhuyin:"ㄌㄢˊ ㄇㄟˊ"},
  {id:"擴充-032",category:"綜合擴充題",answer:"酪梨",emoji:"🥑",hint:"切開中間有大果核",zhuyin:"ㄌㄨㄛˋ ㄌㄧˊ"},
  {id:"擴充-033",category:"綜合擴充題",answer:"小黃瓜",emoji:"🥒",hint:"拿著長長蔬菜咬",zhuyin:"ㄒㄧㄠˇ ㄏㄨㄤˊ ㄍㄨㄚ"},
  {id:"擴充-034",category:"綜合擴充題",answer:"花椰菜",emoji:"🥦",hint:"像一棵綠色小樹",zhuyin:"ㄏㄨㄚ ㄧㄝˊ ㄘㄞˋ"},
  {id:"擴充-035",category:"綜合擴充題",answer:"馬鈴薯",emoji:"🥔",hint:"從泥土挖出圓薯",zhuyin:"ㄇㄚˇ ㄌㄧㄥˊ ㄕㄨˇ"},
  {id:"擴充-036",category:"綜合擴充題",answer:"地瓜",emoji:"🍠",hint:"捧著熱熱的剝皮吃",zhuyin:"ㄉㄧˋ ㄍㄨㄚ"},
  {id:"擴充-037",category:"綜合擴充題",answer:"蘑菇",emoji:"🍄",hint:"頭頂像撐著小傘",zhuyin:"ㄇㄛˊ ㄍㄨ"},
  {id:"擴充-038",category:"綜合擴充題",answer:"起司",emoji:"🧀",hint:"拉出香香的起司絲",zhuyin:"ㄑㄧˇ ㄙ"},
  {id:"擴充-039",category:"綜合擴充題",answer:"漢堡",emoji:"🍔",hint:"雙手拿著大口咬",zhuyin:"ㄏㄢˋ ㄅㄠˇ"},
  {id:"擴充-040",category:"綜合擴充題",answer:"熱狗",emoji:"🌭",hint:"擠上醬料再咬一口",zhuyin:"ㄖㄜˋ ㄍㄡˇ"},
  {id:"擴充-041",category:"綜合擴充題",answer:"壽司",emoji:"🍣",hint:"用筷子夾起小小一塊",zhuyin:"ㄕㄡˋ ㄙ"},
  {id:"擴充-042",category:"綜合擴充題",answer:"蛋糕",emoji:"🍰",hint:"切一塊慢慢品嚐",zhuyin:"ㄉㄢˋ ㄍㄠ"},
  {id:"擴充-043",category:"綜合擴充題",answer:"巧克力",emoji:"🍫",hint:"剝開包裝掰一小塊",zhuyin:"ㄑㄧㄠˇ ㄎㄜˋ ㄌㄧˋ"},
  {id:"擴充-044",category:"綜合擴充題",answer:"糖果",emoji:"🍬",hint:"扭開糖紙放進嘴裡",zhuyin:"ㄊㄤˊ ㄍㄨㄛˇ"},
  {id:"擴充-045",category:"綜合擴充題",answer:"蜂蜜",emoji:"🍯",hint:"舀起黏黏甜甜的蜜",zhuyin:"ㄈㄥ ㄇㄧˋ"},
  {id:"擴充-046",category:"綜合擴充題",answer:"牛奶",emoji:"🥛",hint:"捧杯子大口喝",zhuyin:"ㄋㄧㄡˊ ㄋㄞˇ"},
  {id:"擴充-047",category:"綜合擴充題",answer:"果汁",emoji:"🧃",hint:"插入吸管用力吸",zhuyin:"ㄍㄨㄛˇ ㄓ"},
  {id:"擴充-048",category:"綜合擴充題",answer:"咖啡",emoji:"☕",hint:"捧著熱杯吹一吹",zhuyin:"ㄎㄚ ㄈㄟ"},
  {id:"擴充-049",category:"綜合擴充題",answer:"茶",emoji:"🍵",hint:"端起小杯慢慢喝",zhuyin:"ㄔㄚˊ"},
  {id:"擴充-050",category:"綜合擴充題",answer:"湯",emoji:"🥣",hint:"用湯匙舀起來喝",zhuyin:"ㄊㄤ"},
  {id:"擴充-051",category:"綜合擴充題",answer:"洗臉",emoji:"🧼",hint:"雙手捧水搓搓臉",zhuyin:"ㄒㄧˇ ㄌㄧㄢˇ"},
  {id:"擴充-052",category:"綜合擴充題",answer:"梳頭",emoji:"💇",hint:"拿梳子從頭頂梳下",zhuyin:"ㄕㄨ ㄊㄡˊ"},
  {id:"擴充-053",category:"綜合擴充題",answer:"洗澡",emoji:"🚿",hint:"沖水抹肥皂洗全身",zhuyin:"ㄒㄧˇ ㄗㄠˇ"},
  {id:"擴充-054",category:"綜合擴充題",answer:"穿外套",emoji:"🧥",hint:"手伸進袖子拉拉鍊",zhuyin:"ㄔㄨㄢ ㄨㄞˋ ㄊㄠˋ"},
  {id:"擴充-055",category:"綜合擴充題",answer:"脫襪子",emoji:"🧦",hint:"彎腰把襪子拉下來",zhuyin:"ㄊㄨㄛ ㄨㄚˋ ㄗ˙"},
  {id:"擴充-056",category:"綜合擴充題",answer:"綁鞋帶",emoji:"👟",hint:"蹲下打出蝴蝶結",zhuyin:"ㄅㄤˇ ㄒㄧㄝˊ ㄉㄞˋ"},
  {id:"擴充-057",category:"綜合擴充題",answer:"開門",emoji:"🚪",hint:"轉把手把門推開",zhuyin:"ㄎㄞ ㄇㄣˊ"},
  {id:"擴充-058",category:"綜合擴充題",answer:"關窗",emoji:"🪟",hint:"雙手把窗戶拉起來",zhuyin:"ㄍㄨㄢ ㄔㄨㄤ"},
  {id:"擴充-059",category:"綜合擴充題",answer:"搬箱子",emoji:"📦",hint:"彎腰抱起重箱子",zhuyin:"ㄅㄢ ㄒㄧㄤ ㄗ˙"},
  {id:"擴充-060",category:"綜合擴充題",answer:"擦桌子",emoji:"🧽",hint:"拿抹布左右擦乾淨",zhuyin:"ㄘㄚ ㄓㄨㄛ ㄗ˙"},
  {id:"擴充-061",category:"綜合擴充題",answer:"拖地板",emoji:"🧹",hint:"握長柄前後拖地",zhuyin:"ㄊㄨㄛ ㄉㄧˋ ㄅㄢˇ"},
  {id:"擴充-062",category:"綜合擴充題",answer:"洗碗",emoji:"🍽️",hint:"拿海綿把盤子洗亮",zhuyin:"ㄒㄧˇ ㄨㄢˇ"},
  {id:"擴充-063",category:"綜合擴充題",answer:"摺衣服",emoji:"👕",hint:"把袖子和衣角摺好",zhuyin:"ㄓㄜˊ ㄧ ㄈㄨˊ"},
  {id:"擴充-064",category:"綜合擴充題",answer:"丟垃圾",emoji:"🗑️",hint:"提起垃圾放進桶裡",zhuyin:"ㄉㄧㄡ ㄌㄜˋ ㄙㄜˋ"},
  {id:"擴充-065",category:"綜合擴充題",answer:"整理書桌",emoji:"🗂️",hint:"把東西分類排整齊",zhuyin:"ㄓㄥˇ ㄌㄧˇ ㄕㄨ ㄓㄨㄛ"},
  {id:"擴充-066",category:"綜合擴充題",answer:"削鉛筆",emoji:"✏️",hint:"轉動鉛筆削尖筆頭",zhuyin:"ㄒㄧㄠ ㄑㄧㄢ ㄅㄧˇ"},
  {id:"擴充-067",category:"綜合擴充題",answer:"貼貼紙",emoji:"🏷️",hint:"撕下來對準位置貼好",zhuyin:"ㄊㄧㄝ ㄊㄧㄝ ㄓˇ"},
  {id:"擴充-068",category:"綜合擴充題",answer:"蓋印章",emoji:"🔖",hint:"沾一下再用力蓋下",zhuyin:"ㄍㄞˋ ㄧㄣˋ ㄓㄤ"},
  {id:"擴充-069",category:"綜合擴充題",answer:"畫圓圈",emoji:"⭕",hint:"拿筆繞一圈接回起點",zhuyin:"ㄏㄨㄚˋ ㄩㄢˊ ㄑㄩㄢ"},
  {id:"擴充-070",category:"綜合擴充題",answer:"數手指",emoji:"🖐️",hint:"一根一根慢慢數",zhuyin:"ㄕㄨˇ ㄕㄡˇ ㄓˇ"},
  {id:"擴充-071",category:"綜合擴充題",answer:"吹蠟燭",emoji:"🕯️",hint:"吸一口氣用力吹熄",zhuyin:"ㄔㄨㄟ ㄌㄚˋ ㄓㄨˊ"},
  {id:"擴充-072",category:"綜合擴充題",answer:"許願",emoji:"🌠",hint:"閉上眼睛雙手合起",zhuyin:"ㄒㄩˇ ㄩㄢˋ"},
  {id:"擴充-073",category:"綜合擴充題",answer:"跳舞",emoji:"💃",hint:"跟著節奏扭動身體",zhuyin:"ㄊㄧㄠˋ ㄨˇ"},
  {id:"擴充-074",category:"綜合擴充題",answer:"唱歌",emoji:"🎤",hint:"拿麥克風開心演唱",zhuyin:"ㄔㄤˋ ㄍㄜ"},
  {id:"擴充-075",category:"綜合擴充題",answer:"吹口哨",emoji:"😗",hint:"嘴巴嘟起吹出聲音",zhuyin:"ㄔㄨㄟ ㄎㄡˇ ㄕㄠˋ"},
  {id:"擴充-076",category:"綜合擴充題",answer:"滑滑梯",emoji:"🛝",hint:"爬上去坐著滑下來",zhuyin:"ㄏㄨㄚˊ ㄏㄨㄚˊ ㄊㄧ"},
  {id:"擴充-077",category:"綜合擴充題",answer:"盪鞦韆",emoji:"↔️",hint:"坐好前後盪高高",zhuyin:"ㄉㄤˋ ㄑㄧㄡ ㄑㄧㄢ"},
  {id:"擴充-078",category:"綜合擴充題",answer:"蹺蹺板",emoji:"↕️",hint:"兩人輪流一高一低",zhuyin:"ㄑㄧㄠ ㄑㄧㄠ ㄅㄢˇ"},
  {id:"擴充-079",category:"綜合擴充題",answer:"放風箏",emoji:"🪁",hint:"拉著線迎風奔跑",zhuyin:"ㄈㄤˋ ㄈㄥ ㄓㄥ"},
  {id:"擴充-080",category:"綜合擴充題",answer:"堆沙堡",emoji:"🏖️",hint:"裝滿沙子蓋出城堡",zhuyin:"ㄉㄨㄟ ㄕㄚ ㄅㄠˇ"},
  {id:"擴充-081",category:"綜合擴充題",answer:"玩呼拉圈",emoji:"⭕",hint:"腰部轉動圈圈不停",zhuyin:"ㄨㄢˊ ㄏㄨ ㄌㄚ ㄑㄩㄢ"},
  {id:"擴充-082",category:"綜合擴充題",answer:"踢毽子",emoji:"🪶",hint:"用腳背向上輕踢",zhuyin:"ㄊㄧ ㄐㄧㄢˋ ㄗ˙"},
  {id:"擴充-083",category:"綜合擴充題",answer:"丟沙包",emoji:"🥎",hint:"瞄準目標輕輕丟",zhuyin:"ㄉㄧㄡ ㄕㄚ ㄅㄠ"},
  {id:"擴充-084",category:"綜合擴充題",answer:"捉迷藏",emoji:"🙈",hint:"遮住眼睛再去找人",zhuyin:"ㄓㄨㄛ ㄇㄧˊ ㄘㄤˊ"},
  {id:"擴充-085",category:"綜合擴充題",answer:"猜拳",emoji:"✊",hint:"石頭剪刀布一起出拳",zhuyin:"ㄘㄞ ㄑㄩㄢˊ"},
  {id:"擴充-086",category:"綜合擴充題",answer:"玩積木",emoji:"🧱",hint:"一塊一塊疊高高",zhuyin:"ㄨㄢˊ ㄐㄧ ㄇㄨˋ"},
  {id:"擴充-087",category:"綜合擴充題",answer:"拼拼圖",emoji:"🧩",hint:"轉動小片找到位置",zhuyin:"ㄆㄧㄣ ㄆㄧㄣ ㄊㄨˊ"},
  {id:"擴充-088",category:"綜合擴充題",answer:"下棋",emoji:"♟️",hint:"想一想再移動棋子",zhuyin:"ㄒㄧㄚˋ ㄑㄧˊ"},
  {id:"擴充-089",category:"綜合擴充題",answer:"打鼓",emoji:"🥁",hint:"拿鼓棒左右敲打",zhuyin:"ㄉㄚˇ ㄍㄨˇ"},
  {id:"擴充-090",category:"綜合擴充題",answer:"彈鋼琴",emoji:"🎹",hint:"十根手指輪流按鍵",zhuyin:"ㄊㄢˊ ㄍㄤ ㄑㄧㄣˊ"},
  {id:"擴充-091",category:"綜合擴充題",answer:"拉小提琴",emoji:"🎻",hint:"肩膀夾琴來回拉弓",zhuyin:"ㄌㄚ ㄒㄧㄠˇ ㄊㄧˊ ㄑㄧㄣˊ"},
  {id:"擴充-092",category:"綜合擴充題",answer:"吹笛子",emoji:"🪈",hint:"橫拿笛子按孔吹奏",zhuyin:"ㄔㄨㄟ ㄉㄧˊ ㄗ˙"},
  {id:"擴充-093",category:"綜合擴充題",answer:"唱卡拉OK",emoji:"🎙️",hint:"看著字幕拿麥克風唱",zhuyin:"ㄔㄤˋ ㄎㄚˇ ㄌㄚ O K"},
  {id:"擴充-094",category:"綜合擴充題",answer:"釣魚",emoji:"🎣",hint:"甩出魚線耐心等待",zhuyin:"ㄉㄧㄠˋ ㄩˊ"},
  {id:"擴充-095",category:"綜合擴充題",answer:"露營",emoji:"⛺",hint:"搭起帳篷鑽進去",zhuyin:"ㄌㄨˋ ㄧㄥˊ"},
  {id:"擴充-096",category:"綜合擴充題",answer:"爬山",emoji:"🥾",hint:"背著背包一步步上坡",zhuyin:"ㄆㄚˊ ㄕㄢ"},
  {id:"擴充-097",category:"綜合擴充題",answer:"滑雪",emoji:"⛷️",hint:"拿雪杖左右滑動",zhuyin:"ㄏㄨㄚˊ ㄒㄩㄝˇ"},
  {id:"擴充-098",category:"綜合擴充題",answer:"划船",emoji:"🚣",hint:"雙手握槳往後划",zhuyin:"ㄏㄨㄚˊ ㄔㄨㄢˊ"},
  {id:"擴充-099",category:"綜合擴充題",answer:"打高爾夫",emoji:"🏌️",hint:"瞄準小球揮桿",zhuyin:"ㄉㄚˇ ㄍㄠ ㄦˇ ㄈㄨ"},
  {id:"擴充-100",category:"綜合擴充題",answer:"攀岩",emoji:"🧗",hint:"手腳找支點向上爬",zhuyin:"ㄆㄢ ㄧㄢˊ"},
  {id:"擴充-101",category:"綜合擴充題",answer:"牙醫",emoji:"🦷",hint:"張嘴檢查每顆牙齒",zhuyin:"ㄧㄚˊ ㄧ"},
  {id:"擴充-102",category:"綜合擴充題",answer:"獸醫",emoji:"🐾",hint:"拿聽診器照顧動物",zhuyin:"ㄕㄡˋ ㄧ"},
  {id:"擴充-103",category:"綜合擴充題",answer:"司機",emoji:"🚘",hint:"握方向盤專心開車",zhuyin:"ㄙ ㄐㄧ"},
  {id:"擴充-104",category:"綜合擴充題",answer:"船長",emoji:"🧑‍✈️",hint:"看海圖掌舵前進",zhuyin:"ㄔㄨㄢˊ ㄓㄤˇ"},
  {id:"擴充-105",category:"綜合擴充題",answer:"列車長",emoji:"🚆",hint:"吹哨確認大家上車",zhuyin:"ㄌㄧㄝˋ ㄔㄜ ㄓㄤˇ"},
  {id:"擴充-106",category:"綜合擴充題",answer:"麵包師",emoji:"🥖",hint:"揉麵團送進烤箱",zhuyin:"ㄇㄧㄢˋ ㄅㄠ ㄕ"},
  {id:"擴充-107",category:"綜合擴充題",answer:"花店店員",emoji:"💐",hint:"挑選花朵綁成花束",zhuyin:"ㄏㄨㄚ ㄉㄧㄢˋ ㄉㄧㄢˋ ㄩㄢˊ"},
  {id:"擴充-108",category:"綜合擴充題",answer:"服務生",emoji:"🍽️",hint:"端著托盤送上餐點",zhuyin:"ㄈㄨˊ ㄨˋ ㄕㄥ"},
  {id:"擴充-109",category:"綜合擴充題",answer:"清潔員",emoji:"🧹",hint:"拿工具把地面清乾淨",zhuyin:"ㄑㄧㄥ ㄐㄧㄝˊ ㄩㄢˊ"},
  {id:"擴充-110",category:"綜合擴充題",answer:"建築師",emoji:"📐",hint:"攤開圖紙畫房子",zhuyin:"ㄐㄧㄢˋ ㄓㄨˊ ㄕ"},
  {id:"擴充-111",category:"綜合擴充題",answer:"工程師",emoji:"⚙️",hint:"看圖組裝大型機器",zhuyin:"ㄍㄨㄥ ㄔㄥˊ ㄕ"},
  {id:"擴充-112",category:"綜合擴充題",answer:"程式設計師",emoji:"💻",hint:"盯著螢幕快速打字",zhuyin:"ㄔㄥˊ ㄕˋ ㄕㄜˋ ㄐㄧˋ ㄕ"},
  {id:"擴充-113",category:"綜合擴充題",answer:"氣象播報員",emoji:"🌤️",hint:"指著地圖介紹天氣",zhuyin:"ㄑㄧˋ ㄒㄧㄤˋ ㄅㄛˋ ㄅㄠˋ ㄩㄢˊ"},
  {id:"擴充-114",category:"綜合擴充題",answer:"運動教練",emoji:"🏅",hint:"吹哨示範運動動作",zhuyin:"ㄩㄣˋ ㄉㄨㄥˋ ㄐㄧㄠˋ ㄌㄧㄢˋ"},
  {id:"擴充-115",category:"綜合擴充題",answer:"舞蹈老師",emoji:"🩰",hint:"數著拍子教大家跳舞",zhuyin:"ㄨˇ ㄉㄠˋ ㄌㄠˇ ㄕ"},
  {id:"擴充-116",category:"綜合擴充題",answer:"音樂家",emoji:"🎼",hint:"看著樂譜演奏音樂",zhuyin:"ㄧㄣ ㄩㄝˋ ㄐㄧㄚ"},
  {id:"擴充-117",category:"綜合擴充題",answer:"魔術師",emoji:"🎩",hint:"揮動手變出驚喜",zhuyin:"ㄇㄛˊ ㄕㄨˋ ㄕ"},
  {id:"擴充-118",category:"綜合擴充題",answer:"演員",emoji:"🎭",hint:"換表情演出故事",zhuyin:"ㄧㄢˇ ㄩㄢˊ"},
  {id:"擴充-119",category:"綜合擴充題",answer:"主持人",emoji:"🎙️",hint:"拿麥克風介紹節目",zhuyin:"ㄓㄨˇ ㄔˊ ㄖㄣˊ"},
  {id:"擴充-120",category:"綜合擴充題",answer:"售票員",emoji:"🎟️",hint:"收錢撕下一張票",zhuyin:"ㄕㄡˋ ㄆㄧㄠˋ ㄩㄢˊ"},
  {id:"擴充-121",category:"綜合擴充題",answer:"木匠",emoji:"🪚",hint:"量木板再敲敲組裝",zhuyin:"ㄇㄨˋ ㄐㄧㄤˋ"},
  {id:"擴充-122",category:"綜合擴充題",answer:"陶藝家",emoji:"🏺",hint:"雙手轉動泥土做陶器",zhuyin:"ㄊㄠˊ ㄧˋ ㄐㄧㄚ"},
  {id:"擴充-123",category:"綜合擴充題",answer:"救生員",emoji:"🛟",hint:"在水邊注意大家安全",zhuyin:"ㄐㄧㄡˋ ㄕㄥ ㄩㄢˊ"},
  {id:"擴充-124",category:"綜合擴充題",answer:"園藝師",emoji:"🌱",hint:"修剪枝葉照顧花草",zhuyin:"ㄩㄢˊ ㄧˋ ㄕ"},
  {id:"擴充-125",category:"綜合擴充題",answer:"裁縫師",emoji:"🧵",hint:"拿針線縫製衣服",zhuyin:"ㄘㄞˊ ㄈㄥˊ ㄕ"},
  {id:"擴充-126",category:"綜合擴充題",answer:"熱氣球",emoji:"🎈",hint:"坐進籃子慢慢升空",zhuyin:"ㄖㄜˋ ㄑㄧˋ ㄑㄧㄡˊ"},
  {id:"擴充-127",category:"綜合擴充題",answer:"帆船",emoji:"⛵",hint:"張開船帆乘風前進",zhuyin:"ㄈㄢˊ ㄔㄨㄢˊ"},
  {id:"擴充-128",category:"綜合擴充題",answer:"纜車",emoji:"🚡",hint:"吊在高空緩緩移動",zhuyin:"ㄌㄢˇ ㄔㄜ"},
  {id:"擴充-129",category:"綜合擴充題",answer:"單軌列車",emoji:"🚝",hint:"沿著高架軌道前進",zhuyin:"ㄉㄢ ㄍㄨㄟˇ ㄌㄧㄝˋ ㄔㄜ"},
  {id:"擴充-130",category:"綜合擴充題",answer:"垃圾車",emoji:"🚛",hint:"停下來收走垃圾桶",zhuyin:"ㄌㄜˋ ㄙㄜˋ ㄔㄜ"},
  {id:"擴充-131",category:"綜合擴充題",answer:"郵輪",emoji:"🛳️",hint:"在大船上看海旅行",zhuyin:"ㄧㄡˊ ㄌㄨㄣˊ"},
  {id:"擴充-132",category:"綜合擴充題",answer:"校車",emoji:"🚍",hint:"排隊上車去上學",zhuyin:"ㄒㄧㄠˋ ㄔㄜ"},
  {id:"擴充-133",category:"綜合擴充題",answer:"賽車",emoji:"🏎️",hint:"握方向盤快速過彎",zhuyin:"ㄙㄞˋ ㄔㄜ"},
  {id:"擴充-134",category:"綜合擴充題",answer:"雪橇",emoji:"🛷",hint:"坐好從雪坡滑下",zhuyin:"ㄒㄩㄝˇ ㄑㄧㄠ"},
  {id:"擴充-135",category:"綜合擴充題",answer:"嬰兒車",emoji:"👶",hint:"雙手扶把慢慢推行",zhuyin:"ㄧㄥ ㄦˊ ㄔㄜ"},
  {id:"擴充-136",category:"綜合擴充題",answer:"交通號誌",emoji:"🚦",hint:"紅燈停綠燈走",zhuyin:"ㄐㄧㄠ ㄊㄨㄥ ㄏㄠˋ ㄓˋ"},
  {id:"擴充-137",category:"綜合擴充題",answer:"停車場",emoji:"🅿️",hint:"找空位倒車停好",zhuyin:"ㄊㄧㄥˊ ㄔㄜ ㄔㄤˇ"},
  {id:"擴充-138",category:"綜合擴充題",answer:"加油站",emoji:"⛽",hint:"拿起油槍替車加油",zhuyin:"ㄐㄧㄚ ㄧㄡˊ ㄓㄢˋ"},
  {id:"擴充-139",category:"綜合擴充題",answer:"燈塔",emoji:"💡",hint:"在海邊轉動亮光",zhuyin:"ㄉㄥ ㄊㄚˇ"},
  {id:"擴充-140",category:"綜合擴充題",answer:"瀑布",emoji:"🏞️",hint:"水從高處快速落下",zhuyin:"ㄆㄨˋ ㄅㄨˋ"},
  {id:"擴充-141",category:"綜合擴充題",answer:"沙漠",emoji:"🏜️",hint:"頂著太陽走過沙地",zhuyin:"ㄕㄚ ㄇㄛˋ"},
  {id:"擴充-142",category:"綜合擴充題",answer:"森林",emoji:"🌲",hint:"穿過好多高高樹木",zhuyin:"ㄙㄣ ㄌㄧㄣˊ"},
  {id:"擴充-143",category:"綜合擴充題",answer:"洞穴",emoji:"🕳️",hint:"彎腰小心走進黑洞",zhuyin:"ㄉㄨㄥˋ ㄒㄩㄝˋ"},
  {id:"擴充-144",category:"綜合擴充題",answer:"島嶼",emoji:"🏝️",hint:"四周都是海水",zhuyin:"ㄉㄠˇ ㄩˇ"},
  {id:"擴充-145",category:"綜合擴充題",answer:"冰山",emoji:"🧊",hint:"變成海上巨大冰塊",zhuyin:"ㄅㄧㄥ ㄕㄢ"},
  {id:"擴充-146",category:"綜合擴充題",answer:"雷電",emoji:"⚡",hint:"突然閃亮轟隆一聲",zhuyin:"ㄌㄟˊ ㄉㄧㄢˋ"},
  {id:"擴充-147",category:"綜合擴充題",answer:"濃霧",emoji:"🌫️",hint:"伸手摸索看不清楚",zhuyin:"ㄋㄨㄥˊ ㄨˋ"},
  {id:"擴充-148",category:"綜合擴充題",answer:"夕陽",emoji:"🌇",hint:"太陽慢慢往下沉",zhuyin:"ㄒㄧˋ ㄧㄤˊ"},
  {id:"擴充-149",category:"綜合擴充題",answer:"稻田",emoji:"🌾",hint:"彎腰在田裡收割",zhuyin:"ㄉㄠˋ ㄊㄧㄢˊ"},
  {id:"擴充-150",category:"綜合擴充題",answer:"荷花",emoji:"🪷",hint:"在水面慢慢開花",zhuyin:"ㄏㄜˊ ㄏㄨㄚ"},
  {id:"擴充-151",category:"綜合擴充題",answer:"冰箱",emoji:"🧊",hint:"打開門拿出冰食物",zhuyin:"ㄅㄧㄥ ㄒㄧㄤ"},
  {id:"擴充-152",category:"綜合擴充題",answer:"洗衣機",emoji:"🧺",hint:"放進衣服按鈕轉動",zhuyin:"ㄒㄧˇ ㄧ ㄐㄧ"},
  {id:"擴充-153",category:"綜合擴充題",answer:"電風扇",emoji:"🪭",hint:"對著風吹得頭髮飄",zhuyin:"ㄉㄧㄢˋ ㄈㄥ ㄕㄢˋ"},
  {id:"擴充-154",category:"綜合擴充題",answer:"冷氣機",emoji:"❄️",hint:"按遙控器吹出冷風",zhuyin:"ㄌㄥˇ ㄑㄧˋ ㄐㄧ"},
  {id:"擴充-155",category:"綜合擴充題",answer:"電視",emoji:"📺",hint:"拿遙控器換頻道",zhuyin:"ㄉㄧㄢˋ ㄕˋ"},
  {id:"擴充-156",category:"綜合擴充題",answer:"電腦",emoji:"💻",hint:"打開螢幕操作程式",zhuyin:"ㄉㄧㄢˋ ㄋㄠˇ"},
  {id:"擴充-157",category:"綜合擴充題",answer:"鍵盤",emoji:"⌨️",hint:"十根手指快速敲字",zhuyin:"ㄐㄧㄢˋ ㄆㄢˊ"},
  {id:"擴充-158",category:"綜合擴充題",answer:"滑鼠",emoji:"🖱️",hint:"移動游標按一下",zhuyin:"ㄏㄨㄚˊ ㄕㄨˇ"},
  {id:"擴充-159",category:"綜合擴充題",answer:"耳機",emoji:"🎧",hint:"戴在耳朵聽音樂",zhuyin:"ㄦˇ ㄐㄧ"},
  {id:"擴充-160",category:"綜合擴充題",answer:"相機",emoji:"📷",hint:"拿起來對準按快門",zhuyin:"ㄒㄧㄤˋ ㄐㄧ"},
  {id:"擴充-161",category:"綜合擴充題",answer:"麥克風",emoji:"🎤",hint:"拿在嘴邊大聲說話",zhuyin:"ㄇㄞˋ ㄎㄜˋ ㄈㄥ"},
  {id:"擴充-162",category:"綜合擴充題",answer:"吉他",emoji:"🎸",hint:"一手按弦一手撥弦",zhuyin:"ㄐㄧˊ ㄊㄚ"},
  {id:"擴充-163",category:"綜合擴充題",answer:"爵士鼓",emoji:"🥁",hint:"手腳一起敲出節奏",zhuyin:"ㄐㄩㄝˊ ㄕˋ ㄍㄨˇ"},
  {id:"擴充-164",category:"綜合擴充題",answer:"球拍",emoji:"🎾",hint:"握著拍子揮出去",zhuyin:"ㄑㄧㄡˊ ㄆㄞ"},
  {id:"擴充-165",category:"綜合擴充題",answer:"安全帽",emoji:"⛑️",hint:"戴上頭扣緊帶子",zhuyin:"ㄢ ㄑㄩㄢˊ ㄇㄠˋ"},
  {id:"擴充-166",category:"綜合擴充題",answer:"手套",emoji:"🧤",hint:"五根手指套進去",zhuyin:"ㄕㄡˇ ㄊㄠˋ"},
  {id:"擴充-167",category:"綜合擴充題",answer:"圍巾",emoji:"🧣",hint:"繞著脖子保暖",zhuyin:"ㄨㄟˊ ㄐㄧㄣ"},
  {id:"擴充-168",category:"綜合擴充題",answer:"眼鏡",emoji:"👓",hint:"打開鏡腳戴到臉上",zhuyin:"ㄧㄢˇ ㄐㄧㄥˋ"},
  {id:"擴充-169",category:"綜合擴充題",answer:"牙刷",emoji:"🪥",hint:"擠上牙膏上下移動",zhuyin:"ㄧㄚˊ ㄕㄨㄚ"},
  {id:"擴充-170",category:"綜合擴充題",answer:"肥皂",emoji:"🧼",hint:"加水搓出好多泡泡",zhuyin:"ㄈㄟˊ ㄗㄠˋ"},
  {id:"擴充-171",category:"綜合擴充題",answer:"毛巾",emoji:"🧖",hint:"擦乾臉和雙手",zhuyin:"ㄇㄠˊ ㄐㄧㄣ"},
  {id:"擴充-172",category:"綜合擴充題",answer:"湯匙",emoji:"🥄",hint:"舀起食物送進嘴裡",zhuyin:"ㄊㄤ ㄔˊ"},
  {id:"擴充-173",category:"綜合擴充題",answer:"叉子",emoji:"🍴",hint:"叉起食物慢慢吃",zhuyin:"ㄔㄚ ㄗ˙"},
  {id:"擴充-174",category:"綜合擴充題",answer:"筷子",emoji:"🥢",hint:"兩根一起夾起食物",zhuyin:"ㄎㄨㄞˋ ㄗ˙"},
  {id:"擴充-175",category:"綜合擴充題",answer:"飯碗",emoji:"🥣",hint:"一手捧碗一手吃飯",zhuyin:"ㄈㄢˋ ㄨㄢˇ"},
  {id:"擴充-176",category:"綜合擴充題",answer:"過生日",emoji:"🎂",hint:"戴帽子接受大家祝福",zhuyin:"ㄍㄨㄛˋ ㄕㄥ ㄖˋ"},
  {id:"擴充-177",category:"綜合擴充題",answer:"上學",emoji:"🏫",hint:"背著書包走進校門",zhuyin:"ㄕㄤˋ ㄒㄩㄝˊ"},
  {id:"擴充-178",category:"綜合擴充題",answer:"放學",emoji:"🔔",hint:"收好書包開心回家",zhuyin:"ㄈㄤˋ ㄒㄩㄝˊ"},
  {id:"擴充-179",category:"綜合擴充題",answer:"等公車",emoji:"🚏",hint:"站在站牌伸頭張望",zhuyin:"ㄉㄥˇ ㄍㄨㄥ ㄔㄜ"},
  {id:"擴充-180",category:"綜合擴充題",answer:"排隊",emoji:"🚶",hint:"跟在前面的人後方",zhuyin:"ㄆㄞˊ ㄉㄨㄟˋ"},
  {id:"擴充-181",category:"綜合擴充題",answer:"買東西",emoji:"🛒",hint:"推著推車挑選商品",zhuyin:"ㄇㄞˇ ㄉㄨㄥ ㄒㄧ"},
  {id:"擴充-182",category:"綜合擴充題",answer:"結帳",emoji:"💳",hint:"拿商品排隊付錢",zhuyin:"ㄐㄧㄝˊ ㄓㄤˋ"},
  {id:"擴充-183",category:"綜合擴充題",answer:"寄信",emoji:"✉️",hint:"貼上郵票放進郵筒",zhuyin:"ㄐㄧˋ ㄒㄧㄣˋ"},
  {id:"擴充-184",category:"綜合擴充題",answer:"收包裹",emoji:"📦",hint:"簽名後開心接過箱子",zhuyin:"ㄕㄡ ㄅㄠ ㄍㄨㄛˇ"},
  {id:"擴充-185",category:"綜合擴充題",answer:"迷路",emoji:"🗺️",hint:"看四周不知道往哪走",zhuyin:"ㄇㄧˊ ㄌㄨˋ"},
  {id:"擴充-186",category:"綜合擴充題",answer:"問路",emoji:"🧭",hint:"指著方向向別人詢問",zhuyin:"ㄨㄣˋ ㄌㄨˋ"},
  {id:"擴充-187",category:"綜合擴充題",answer:"搭電梯",emoji:"🛗",hint:"按按鈕等門打開",zhuyin:"ㄉㄚ ㄉㄧㄢˋ ㄊㄧ"},
  {id:"擴充-188",category:"綜合擴充題",answer:"走樓梯",emoji:"🚶",hint:"一步一階向上走",zhuyin:"ㄗㄡˇ ㄌㄡˊ ㄊㄧ"},
  {id:"擴充-189",category:"綜合擴充題",answer:"過馬路",emoji:"🚸",hint:"左右看再走斑馬線",zhuyin:"ㄍㄨㄛˋ ㄇㄚˇ ㄌㄨˋ"},
  {id:"擴充-190",category:"綜合擴充題",answer:"野餐",emoji:"🧺",hint:"鋪墊子坐下分享食物",zhuyin:"ㄧㄝˇ ㄘㄢ"},
  {id:"擴充-191",category:"綜合擴充題",answer:"看電影",emoji:"🎬",hint:"坐著盯大螢幕吃點心",zhuyin:"ㄎㄢˋ ㄉㄧㄢˋ ㄧㄥˇ"},
  {id:"擴充-192",category:"綜合擴充題",answer:"看煙火",emoji:"🎆",hint:"抬頭看天空綻放亮光",zhuyin:"ㄎㄢˋ ㄧㄢ ㄏㄨㄛˇ"},
  {id:"擴充-193",category:"綜合擴充題",answer:"堆雪人",emoji:"⛄",hint:"滾兩顆雪球疊起來",zhuyin:"ㄉㄨㄟ ㄒㄩㄝˇ ㄖㄣˊ"},
  {id:"擴充-194",category:"綜合擴充題",answer:"抓蝴蝶",emoji:"🦋",hint:"拿網子輕輕追著跑",zhuyin:"ㄓㄨㄚ ㄏㄨˊ ㄉㄧㄝˊ"},
  {id:"擴充-195",category:"綜合擴充題",answer:"餵小鳥",emoji:"🐦",hint:"撒小種子讓鳥來吃",zhuyin:"ㄨㄟˋ ㄒㄧㄠˇ ㄋㄧㄠˇ"},
  {id:"擴充-196",category:"綜合擴充題",answer:"逗小狗",emoji:"🐕",hint:"拿玩具吸引牠玩",zhuyin:"ㄉㄡˋ ㄒㄧㄠˇ ㄍㄡˇ"},
  {id:"擴充-197",category:"綜合擴充題",answer:"照顧寶寶",emoji:"🍼",hint:"抱著輕拍哄入睡",zhuyin:"ㄓㄠˋ ㄍㄨˋ ㄅㄠˇ ㄅㄠ˙"},
  {id:"擴充-198",category:"綜合擴充題",answer:"打包行李",emoji:"🧳",hint:"把衣物放進箱子",zhuyin:"ㄉㄚˇ ㄅㄠ ㄒㄧㄥˊ ㄌㄧˇ"},
  {id:"擴充-199",category:"綜合擴充題",answer:"開心大笑",emoji:"😄",hint:"抱著肚子哈哈大笑",zhuyin:"ㄎㄞ ㄒㄧㄣ ㄉㄚˋ ㄒㄧㄠˋ"},
  {id:"擴充-200",category:"綜合擴充題",answer:"拍團體照",emoji:"🤳",hint:"大家靠近一起看鏡頭",zhuyin:"ㄆㄞ ㄊㄨㄢˊ ㄊㄧˇ ㄓㄠˋ"}
]);
